

spring:
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dolphin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 111111
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    minEvictableIdleTimeMillis: 300000
    filters: stat,wall,log4j2
    poolPreparedStatements: true
    testOnBorrow: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false